version: '3.1'
services:
  mysql:
    container_name: mysql
    image: 'mysql/mysql-server:5.7'
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3306:3306
    volumes:
      - /opt/docker/mysql/log:/var/log/mysql
      - /opt/docker/mysql/data:/var/lib/mysql
      - /opt/docker/mysql/conf:/etc/mysql